# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/07b0a626-cbfb-4f9e-ae2d-ee488441ceac";
      fsType = "ext4";
    };  

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9f181965-f48e-4e6e-8dcf-e00695fda38c";
      fsType = "ext4";
    };  

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/37C9-C571";
      fsType = "vfat";
    };  

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0e5f0870-489a-455d-bf56-28eccde7c6ce"; }
    ];

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/3DC7196A3AF67751";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000"];
    };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;
}

